name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up a PureScript toolchain
        uses: purescript-contrib/setup-purescript@main
        with:
          purescript: "latest"
          purs-tidy: "0.11.0" # "latest"
          spago: "unstable"

      - name: Cache PureScript dependencies
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/spago.lock') }}
          path: |
            .spago
            output

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build source
        run: spago build --censor-stats --strict --ensure-ranges --pedantic-packages

      - name: Run tests
        run: spago test --offline --censor-stats --strict --pedantic-packages

      - name: Verify formatting
        run: purs-tidy check src test examples

      - name: Lint javascript
        run: eslint

      - name: Test examples
        run: npm run examples
